// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqKn8fUozSyeeOGnTiCwY4_bNp6T0zFRc',
    appId: '1:293619476498:web:6758e9e37bed0ddd07d0cb',
    messagingSenderId: '293619476498',
    projectId: 'live-chat-997f9',
    authDomain: 'live-chat-997f9.firebaseapp.com',
    storageBucket: 'live-chat-997f9.appspot.com',
    measurementId: 'G-RLB7Q7GHTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEgs_ewmjXRAm38mrcS1udbUlIdzi7XuA',
    appId: '1:293619476498:android:1f1e446b5f199fca07d0cb',
    messagingSenderId: '293619476498',
    projectId: 'live-chat-997f9',
    storageBucket: 'live-chat-997f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdUfCE4VQSEnDQhqxfZlH5oNd4ppckpc',
    appId: '1:293619476498:ios:bf6b35571cb3d50307d0cb',
    messagingSenderId: '293619476498',
    projectId: 'live-chat-997f9',
    storageBucket: 'live-chat-997f9.appspot.com',
    iosClientId: '293619476498-k3452jgmmdfkksg2jh3bl9om5a1ad27k.apps.googleusercontent.com',
    iosBundleId: 'com.example.livechat',
  );
}
